// packages/widget/examples/vue/KanFeedbackWidget.vue
<!--
  Vue 3 integration for @kanbn/feedback-widget

  Usage:
    <script setup>
    import KanFeedbackWidget from "@/components/KanFeedbackWidget.vue";
    </script>

    <template>
      <YourApp />
      <KanFeedbackWidget
        api-key="kan_abc123..."
        board-id="your-board-id"
        server-url="https://your-kan-instance.com"
        user-name="Jane Doe"
        user-email="jane@example.com"
      />
    </template>

  For Nuxt 3, place this component in components/ and it will be
  auto-imported. Use <ClientOnly> if you encounter SSR issues:

    <ClientOnly>
      <KanFeedbackWidget ... />
    </ClientOnly>
-->

<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from "vue";

const props = defineProps<{
  apiKey: string;
  boardId: string;
  serverUrl: string;
  position?: "bottom-right" | "bottom-left" | "top-right" | "top-left";
  accentColor?: string;
  greeting?: string;
  userName?: string;
  userEmail?: string;
  maxAttachmentBytes?: number;
}>();

const widget = ref<any>(null);

onMounted(async () => {
  const { KanWidget } = await import("@kanbn/feedback-widget");
  widget.value = KanWidget.init({
    apiKey: props.apiKey,
    boardId: props.boardId,
    serverUrl: props.serverUrl,
    position: props.position,
    accentColor: props.accentColor,
    greeting: props.greeting,
    userName: props.userName,
    userEmail: props.userEmail,
    maxAttachmentBytes: props.maxAttachmentBytes,
  });
});

onBeforeUnmount(() => {
  widget.value?.destroy();
  widget.value = null;
});
</script>

<template>
  <!-- Widget renders itself via Shadow DOM, no template needed -->
</template>

// packages/widget/examples/svelte/KanFeedbackWidget.svelte
<!--
  Svelte integration for @kanbn/feedback-widget

  Usage:
    <script>
    import KanFeedbackWidget from "$lib/KanFeedbackWidget.svelte";
    </script>

    <KanFeedbackWidget
      apiKey="kan_abc123..."
      boardId="your-board-id"
      serverUrl="https://your-kan-instance.com"
      userName="Jane Doe"
      userEmail="jane@example.com"
    />

  For SvelteKit, this works as-is. The dynamic import ensures
  the widget only loads on the client side.
-->

<script lang="ts">
  import { onMount, onDestroy } from "svelte";

  export let apiKey: string;
  export let boardId: string;
  export let serverUrl: string;
  export let position: "bottom-right" | "bottom-left" | "top-right" | "top-left" = "bottom-right";
  export let accentColor: string | undefined = undefined;
  export let greeting: string | undefined = undefined;
  export let userName: string | undefined = undefined;
  export let userEmail: string | undefined = undefined;
  export let maxAttachmentBytes: number | undefined = undefined;

  let widget: any = null;

  onMount(async () => {
    const { KanWidget } = await import("@kanbn/feedback-widget");
    widget = KanWidget.init({
      apiKey,
      boardId,
      serverUrl,
      position,
      accentColor,
      greeting,
      userName,
      userEmail,
      maxAttachmentBytes,
    });
  });

  onDestroy(() => {
    widget?.destroy();
    widget = null;
  });
</script>

<!-- Widget renders itself via Shadow DOM, no markup needed -->
